[package]
name = "lights"
version = "0.1.0"
authors = ["sean"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "*"
